 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/boards", type: :request do
  
  # Board. As you add validations to Board, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: "My Board", email: "myemail@onesteptechnical.com", width: 10, height: 10, number_of_mines: 2}
  }

  let(:invalid_attributes) {
    {name: :invalid, email: 12, width: :invalid, height: :invalid, number_of_mines: :invalid}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Board.create! valid_attributes
      get boards_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      board = Board.create! valid_attributes
      get board_url(board)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_board_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      board = Board.create! valid_attributes
      get edit_board_url(board)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Board" do
        expect {
          post boards_url, params: { board: valid_attributes }
        }.to change(Board, :count).by(1)
      end

      it "redirects to the created board" do
        post boards_url, params: { board: valid_attributes }
        expect(response).to redirect_to(board_url(Board.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Board" do
        expect {
          post boards_url, params: { board: invalid_attributes }
        }.to change(Board, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post boards_url, params: { board: invalid_attributes }
        expect(response).to be_unprocessable
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {name: "NewName"}
      }

      it "updates the requested board" do
        board = Board.create! valid_attributes
        patch board_url(board), params: { board: new_attributes }
        board.reload
        expect(board.name).to eq "NewName"
      end

      it "redirects to the board" do
        board = Board.create! valid_attributes
        patch board_url(board), params: { board: new_attributes }
        board.reload
        expect(response).to redirect_to(board_url(board))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        board = Board.create! valid_attributes
        patch board_url(board), params: { board: invalid_attributes }
        expect(response).to be_unprocessable
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested board" do
      board = Board.create! valid_attributes
      expect {
        delete board_url(board)
      }.to change(Board, :count).by(-1)
    end

    it "redirects to the boards list" do
      board = Board.create! valid_attributes
      delete board_url(board)
      expect(response).to redirect_to(boards_url)
    end
  end
end
